export const ENGLISH_WORDS = [
  { syntax: "the", popularity: 10 },
  { syntax: "of", popularity: 10 },
  { syntax: "and", popularity: 10 },
  { syntax: "you", popularity: 10 },
  { syntax: "have", popularity: 50 },
  { syntax: "number", popularity: 100 },
  { syntax: "would", popularity: 100 },
  { syntax: "make", popularity: 100 },
  { syntax: "back", popularity: 200 },
  { syntax: "work", popularity: 200 },
  { syntax: "something", popularity: 200 },
  { syntax: "woman", popularity: 200 },
  { syntax: "much", popularity: 200 },
  { syntax: "become", popularity: 200 },
  { syntax: "student", popularity: 200 },
  { syntax: "anything", popularity: 300 },
  { syntax: "room", popularity: 300 },
  { syntax: "understand", popularity: 300 },
  { syntax: "young", popularity: 300 },
  { syntax: "mother", popularity: 300 },
  { syntax: "information", popularity: 500 },
];
